# Generated by Django 4.0 on 2021-12-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='status',
            field=models.IntegerField(choices=[(0, 'DEAD'), (1, 'ALIVE')], default=1),
        ),
    ]
